### ISSUE TITLE
JWT command on Windows not parsing ACL flag JSON

### ISSUE THREAD

**Issue by abdulajet** [Vonage/vonage-cli#45] opened 2022-01-11 17:14 UTC
![image](https://user-images.githubusercontent.com/15106299/148989667-3ed2b74a-6b73-4500-bde7-7b8a424ae396.png)

Seems that the JSON on windows might need to be escaped?

I managed to get my windows machine to generate one using:

```
vonage jwt --key_file=./my_sample_app.key --acl="{\"paths\":{\"\/*\/users\/**\":{},\"\/*\/conversations\/**\":{},\"\/*\/sessions\/**\":{},\"\/*\/devices\/**\":{},\"\/*\/image\/**\":{},\"\/*\/media\/**\":{},\"\/*\/applications\/**\":{},\"\/*\/push\/**\":{},\"\/*\/knocking\/**\":{},\"\/*\/legs\/**\":{}}}" --subject=Alice --app_id=MY_APP_ID
```

**Comment by manchuck** [comment] 2024-03-20 18:22
@abdulajet closing this bug. We know the issue is about how the ACL is escaped and not an issue with the CLI

**Closed by manchuck** 2024-03-20 18:22 UTC
Labels: bug
